import React, { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'

const fallbackTheme = { brand: { brandName: 'HOLO Print', primary: '#18a7d0', accent: '#111827', background: '#ffffff', text: '#111827', logoUrl: '' }, layout: { showSearch: true, showCollectionPoints: true, takeoverHomepage: true }, sections: [] }
function clean(value, fallback = '') { return typeof value === 'string' && value.trim() ? value.trim() : fallback }
function isHomePath() { return typeof window !== 'undefined' && (window.location.pathname === '/' || window.location.pathname === '') }
function tenantSlug() { if (typeof window === 'undefined') return 'holo-print'; return window.__HOLO_TENANT_SLUG || import.meta.env.VITE_TENANT_SLUG || new URLSearchParams(window.location.search).get('tenantSlug') || 'holo-print' }
function channelSlug() { if (typeof window === 'undefined') return 'default-store'; return window.__HOLO_CHANNEL_SLUG || import.meta.env.VITE_CHANNEL_SLUG || new URLSearchParams(window.location.search).get('channelSlug') || 'default-store' }
function apiBase() { return (import.meta.env.VITE_INTERNAL_STOREFRONT_API_BASE || '').replace(/\/$/, '') }
function themeUrl() { const params = new URLSearchParams({ tenantSlug: tenantSlug(), channelSlug: channelSlug() }); return `${apiBase()}/api/internal/storefront/theme-settings?${params.toString()}` }
function applyBrand(brand = {}) { const root = document.documentElement; const primary = clean(brand.primary, '#18a7d0'); const accent = clean(brand.accent, '#111827'); const bg = clean(brand.background, '#ffffff'); const text = clean(brand.text, '#111827'); root.style.setProperty('--holo-theme-primary', primary); root.style.setProperty('--holo-theme-accent', accent); root.style.setProperty('--holo-theme-background', bg); root.style.setProperty('--holo-theme-text', text); }
function setHomepageTakeover(active) { if (typeof document === 'undefined') return; document.documentElement.dataset.holoThemeHomepage = active ? 'takeover' : 'normal'; let style = document.getElementById('holo-theme-takeover-style'); if (!style) { style = document.createElement('style'); style.id = 'holo-theme-takeover-style'; document.head.appendChild(style); } style.textContent = active ? `#holo-hosted-theme-sections{display:block}#holo-hosted-theme-sections ~ div > section,#holo-hosted-theme-sections ~ section{display:none!important}#holo-hosted-theme-sections ~ div section[data-holo-keep],#holo-hosted-theme-sections ~ footer{display:block!important}` : ''; }
function usePortalHost() { const [host, setHost] = useState(null); useEffect(() => { const ensure = () => { if (!isHomePath()) { setHost(null); setHomepageTakeover(false); return; } let node = document.getElementById('holo-hosted-theme-sections'); if (!node) { node = document.createElement('div'); node.id = 'holo-hosted-theme-sections'; const header = document.querySelector('#root header'); if (header?.parentNode) header.parentNode.insertBefore(node, header.nextSibling); else document.getElementById('root')?.prepend(node); } setHost(node); }; ensure(); window.addEventListener('popstate', ensure); window.addEventListener('locationchange', ensure); const timer = window.setInterval(ensure, 1500); return () => { window.removeEventListener('popstate', ensure); window.removeEventListener('locationchange', ensure); window.clearInterval(timer); }; }, []); return host; }
export default function HostedThemeRuntime() { const [theme, setTheme] = useState(fallbackTheme); const [loaded, setLoaded] = useState(false); const host = usePortalHost(); useEffect(() => { let alive = true; fetch(themeUrl(), { cache: 'no-store' }).then((res) => res.json()).then((payload) => { if (!alive) return; const data = payload?.data || fallbackTheme; setTheme({ ...fallbackTheme, ...data, brand: { ...fallbackTheme.brand, ...(data.brand || {}) }, layout: { ...fallbackTheme.layout, ...(data.layout || {}) }, sections: Array.isArray(data.sections) ? data.sections : [] }); setLoaded(true); }).catch(() => setLoaded(true)); return () => { alive = false; }; }, []); useEffect(() => { applyBrand(theme.brand); }, [theme]); const visibleSections = useMemo(() => (theme.sections || []).filter((section) => section?.enabled !== false), [theme]); useEffect(() => { setHomepageTakeover(Boolean(host && loaded && visibleSections.length && theme.layout?.takeoverHomepage !== false)); return () => setHomepageTakeover(false); }, [host, loaded, visibleSections.length, theme.layout?.takeoverHomepage]); if (!host || !loaded || !visibleSections.length) return null; return createPortal(<div className="holo-theme-runtime" style={{ background: theme.brand?.background || '#ffffff', color: theme.brand?.text || '#111827' }}><RuntimeHeaderNotice theme={theme} />{visibleSections.map((section) => <ThemeSection key={section.id || `${section.type}-${section.title}`} section={section} brand={theme.brand || fallbackTheme.brand} />)}</div>, host); }
function RuntimeHeaderNotice({ theme }) { if (typeof window !== 'undefined' && !window.location.search.includes('themeDebug=1')) return null; return <div className="mx-auto my-3 max-w-[1360px] rounded-full border bg-white px-4 py-2 text-xs font-bold" style={{ borderColor: '#e3e8f0', color: theme.brand?.primary || '#18a7d0' }}>Hosted theme renderer active · {theme.channelSlug || 'default-store'} · draft v{theme.draftVersion || 0}</div> }
function ThemeSection({ section, brand }) { if (section.type === 'hero') return <HeroSection section={section} brand={brand} />; if (section.type === 'product-grid') return <ProductGridSection section={section} brand={brand} />; if (section.type === 'category-carousel') return <CategorySection section={section} brand={brand} />; if (section.type === 'faq') return <FaqSection section={section} brand={brand} />; if (section.type === 'contact-cta') return <ContactSection section={section} brand={brand} />; if (section.type === 'collection-points') return <CollectionSection section={section} brand={brand} />; return <TextImageSection section={section} brand={brand} />; }
function Shell({ children }) { return <div className="mx-auto w-full max-w-[1360px] px-4 sm:px-6 lg:px-8">{children}</div> }
function HeroSection({ section, brand }) { return <section className="py-8"><Shell><div className="rounded-[28px] border bg-white p-8 shadow-[0_18px_44px_rgba(0,0,0,0.06)]" style={{ borderColor: '#e3e8f0' }}><div className="max-w-[760px]"><p className="text-xs font-bold uppercase tracking-[0.18em]" style={{ color: brand.primary }}>{clean(section.eyebrow, brand.brandName || 'Hosted theme')}</p><h1 className="mt-3 text-[42px] font-black leading-[1.04] tracking-[-0.045em]" style={{ color: brand.text }}>{clean(section.title, 'Your storefront headline')}</h1><p className="mt-4 max-w-[620px] text-sm leading-7 opacity-75">{clean(section.subtitle, 'Add a short supporting message in Site Designer.')}</p>{section.buttonLabel ? <a href={section.buttonHref || '/products'} className="mt-6 inline-flex rounded-full px-5 py-3 text-sm font-bold text-white" style={{ background: brand.primary }}>{section.buttonLabel}</a> : null}</div></div></Shell></section> }
function ProductGridSection({ section, brand }) { const slugs = Array.isArray(section.productSlugs) ? section.productSlugs : []; return <section className="py-6"><Shell><h2 className="text-2xl font-black" style={{ color: brand.text }}>{clean(section.title, 'Featured products')}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{(slugs.length ? slugs : ['standard-business-cards', 'a5-leaflets']).map((slug) => <a key={slug} href={`/${slug}`} className="rounded-[22px] border bg-white p-5 shadow-[0_12px_28px_rgba(0,0,0,0.04)]" style={{ borderColor: '#e3e8f0' }}><p className="text-sm font-bold capitalize" style={{ color: brand.text }}>{slug.replace(/-/g, ' ')}</p><p className="mt-2 text-xs opacity-70">View product</p></a>)}</div></Shell></section> }
function CategorySection({ section, brand }) { const cats = Array.isArray(section.categorySlugs) ? section.categorySlugs : ['business-cards', 'leaflets', 'posters']; return <section className="py-6"><Shell><h2 className="text-2xl font-black" style={{ color: brand.text }}>{clean(section.title, 'Shop by category')}</h2><div className="mt-4 flex gap-3 overflow-x-auto pb-2">{cats.map((slug) => <a key={slug} href={`/${slug}`} className="whitespace-nowrap rounded-full border bg-white px-4 py-2 text-sm font-semibold capitalize" style={{ borderColor: '#e3e8f0', color: brand.text }}>{slug.replace(/-/g, ' ')}</a>)}</div></Shell></section> }
function TextImageSection({ section, brand }) { return <section className="py-6"><Shell><div className="grid gap-6 rounded-[24px] border bg-white p-6 md:grid-cols-2" style={{ borderColor: '#e3e8f0' }}><div><h2 className="text-2xl font-black" style={{ color: brand.text }}>{clean(section.title, 'Section title')}</h2><p className="mt-3 text-sm leading-7 opacity-75">{clean(section.subtitle, 'Section copy goes here.')}</p></div>{section.imageUrl ? <img src={section.imageUrl} alt="" className="h-64 w-full rounded-[18px] object-cover" /> : <div className="h-64 rounded-[18px]" style={{ background: `${brand.primary}22` }} />}</div></Shell></section> }
function FaqSection({ section, brand }) { const items = Array.isArray(section.items) ? section.items : []; return <section className="py-6"><Shell><h2 className="text-2xl font-black" style={{ color: brand.text }}>{clean(section.title, 'Questions and answers')}</h2><div className="mt-4 grid gap-3">{(items.length ? items : [{ question: 'Can I edit this?', answer: 'Yes, from Site Designer.' }]).map((item, index) => <div key={index} className="rounded-[18px] border bg-white p-4" style={{ borderColor: '#e3e8f0' }}><p className="font-bold" style={{ color: brand.text }}>{item.question}</p><p className="mt-2 text-sm opacity-75">{item.answer}</p></div>)}</div></Shell></section> }
function ContactSection({ section, brand }) { return <section className="py-6"><Shell><div className="rounded-[24px] p-6 text-white" style={{ background: `linear-gradient(135deg, ${brand.primary}, ${brand.accent})` }}><h2 className="text-2xl font-black">{clean(section.title, 'Need help?')}</h2><p className="mt-2 text-sm opacity-85">{clean(section.subtitle, 'Send us your artwork or brief.')}</p></div></Shell></section> }
function CollectionSection({ section, brand }) { return <section className="py-6"><Shell><div className="rounded-[24px] border bg-white p-6" style={{ borderColor: '#e3e8f0' }}><h2 className="text-2xl font-black" style={{ color: brand.text }}>{clean(section.title, 'Collection points')}</h2><p className="mt-2 text-sm opacity-75">Collection point content will render from the platform location service.</p></div></Shell></section> }
