import React, { useEffect, useState } from "react";
import { Copy, ExternalLink, PackageCheck, QrCode } from "lucide-react";
import { getCustomerEmail, openOrderDocument } from "./services_api";
import { buildOrderVatSummary, formatCurrency, moneyFromMinor } from "./utils/orderVat";

const API_BASE = import.meta.env.VITE_INTERNAL_STOREFRONT_BASE_URL || import.meta.env.VITE_ADMIN_BASE_URL || import.meta.env.VITE_INTERNAL_API_BASE || import.meta.env.VITE_API_URL || '';
function currency(v){return formatCurrency(v);}
function nice(value){return String(value||'').replace(/_/g,' ').replace(/-/g,' ');}
function tone(status){const s=String(status||'').toLowerCase();if(s.includes('approved')||s.includes('production')||s.includes('dispatch')||s.includes('paid')||s.includes('ready'))return '#059669';if(s.includes('pending')||s.includes('await')||s.includes('quality')||s.includes('not ready'))return '#B45309';if(s.includes('reject')||s.includes('replacement')||s.includes('block')||s.includes('fail')||s.includes('refund')||s.includes('cancel'))return '#DC2626';return '#18A7D0';}
function Card({title,children}){return <div className="p-4 border rounded-[16px] bg-white" style={{borderColor:'#E3E8F0'}}><b>{title}</b><div className="mt-2 text-[12px] leading-6 text-[#667487]">{children}</div></div>}
function Step({label,active}){return <div className="text-center p-3 border rounded-[14px]" style={{borderColor:active?'#18A7D0':'#E2E6E8',background:active?'#EAF7FC':'white',color:active?'#127B98':'#667487'}}><div className="text-[10px] font-bold uppercase tracking-[0.1em]">{label}</div></div>}
function buildUrl(path, params={}){const base=API_BASE.replace(/\/$/,'');const url=new URL(`${base}${path}`,window.location.origin);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,String(v));});return url.toString();}
function qrImageUrl(pass){return pass?.qrUrl?`https://api.qrserver.com/v1/create-qr-code/?size=190x190&margin=12&data=${encodeURIComponent(pass.qrUrl)}`:'';}
function copy(value){try{navigator.clipboard?.writeText(String(value||''));}catch{}}

async function loadCollectionPass(order){const id=order?.id||order?.orderNumber;if(!id)return null;const email=order?.customer?.email||order?.customerEmail||getCustomerEmail()||'';const response=await fetch(buildUrl(`/api/internal/storefront/customer/orders/${encodeURIComponent(id)}/collection-pass`,{email}),{credentials:'include'});const payload=await response.json().catch(()=>null);if(!response.ok||payload?.ok===false)throw new Error(payload?.error||'Collection pass unavailable.');return payload?.data||payload;}

function VatSummary({order}){const t=buildOrderVatSummary(order);return <Card title="VAT summary"><div className="grid gap-2"><div className="flex justify-between"><span>Net total</span><b className="text-[#161A22]">{currency(t.net)}</b></div><div className="flex justify-between"><span>VAT total</span><b className="text-[#161A22]">{currency(t.vat)}</b></div><div className="flex justify-between"><span>Delivery gross</span><b className="text-[#161A22]">{currency(t.delivery)}</b></div><div className="flex justify-between border-t pt-2" style={{borderColor:'#E3E8F0'}}><span>Total inc. VAT</span><b className="text-[#161A22]">{currency(t.gross)}</b></div>{t.hasBreakdown?<div className="mt-2 rounded-[12px] border bg-[#FBFCFF] px-3 py-2" style={{borderColor:'#E3E8F0'}}><div className="font-bold text-[#161A22]">{t.isMixedVat?'Mixed VAT breakdown':'VAT breakdown'}</div>{t.breakdown.map((row)=><div key={`${row.rate}-${row.label}`} className="mt-1 grid grid-cols-3 gap-2"><span>{row.label}</span><span className="text-right">VAT {currency(row.vat)}</span><span className="text-right">Gross {currency(row.gross)}</span></div>)}</div>:<div className="mt-2">VAT breakdown will appear once the order is fully synced.</div>}</div></Card>}

function CollectionPassCard({passState}){const pass=passState?.pass; if(passState?.loading)return <Card title="Collection pass"><div>Loading collection PIN...</div></Card>; if(passState?.reason==='not-a-collection-order'||passState?.available===false)return null; if(!pass)return <Card title="Collection pass"><div>{passState?.error||'Collection pass will appear for collection orders.'}</div></Card>; const ready=pass.status==='ready'||pass.status==='collected';return <Card title="Collection pass"><div className="grid gap-4 md:grid-cols-[210px_1fr]"><div className="rounded-[18px] border bg-[#FBFCFF] p-3 text-center" style={{borderColor:'#E3E8F0'}}>{pass.qrUrl?<img src={qrImageUrl(pass)} alt="Collection QR code" className="mx-auto h-[190px] w-[190px] rounded-xl bg-white" />:<QrCode className="mx-auto h-24 w-24" />}<div className="mt-2 text-[10px] uppercase tracking-[0.12em]">QR scan link</div></div><div><div className="text-[10px] font-bold uppercase tracking-[0.16em]" style={{color:ready?'#059669':'#B45309'}}>{ready?'Ready for handover':'Not ready yet'}</div><div className="mt-2 rounded-[18px] border bg-white p-4 text-center" style={{borderColor:'#E3E8F0'}}><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#667487]">Collection PIN</div><div className="mt-1 text-[34px] font-black tracking-[0.16em] text-[#161A22]">{pass.pin}</div></div><div className="mt-3 grid gap-1"><div><b className="text-[#161A22]">Location:</b> {pass.locationLabel||'Collection point'}</div>{pass.locationAddress?<div><b className="text-[#161A22]">Address:</b> {pass.locationAddress}</div>:null}<div><b className="text-[#161A22]">Instructions:</b> {pass.pickupInstructions}</div>{pass.collectionTruth?<div><b className="text-[#161A22]">Note:</b> {pass.collectionTruth}</div>:null}</div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>copy(pass.pin)} className="inline-flex items-center gap-1 rounded-full border px-3 py-2 text-[11px] font-bold uppercase tracking-[0.08em]"><Copy className="h-3.5 w-3.5" /> Copy PIN</button>{pass.qrUrl?<a href={pass.qrUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full border px-3 py-2 text-[11px] font-bold uppercase tracking-[0.08em]"><ExternalLink className="h-3.5 w-3.5" /> Open pass</a>:null}</div></div></div></Card>}

export default function OrderDetail({order,navigate}){
  const [passState,setPassState]=useState({loading:false,available:false,pass:null,reason:'',error:''});
  useEffect(()=>{let cancelled=false;async function run(){if(!order)return;setPassState((p)=>({...p,loading:true,error:''}));try{const data=await loadCollectionPass(order);if(cancelled)return;setPassState({loading:false,available:!!data.available,pass:data.pass||null,reason:data.reason||'',error:''});}catch(error){if(cancelled)return;setPassState({loading:false,available:false,pass:null,reason:'',error:error instanceof Error?error.message:'Collection pass unavailable.'});}}void run();return()=>{cancelled=true};},[order?.id,order?.orderNumber]);
  if(!order){return <div className="p-6">No order selected. <button onClick={()=>navigate('/account')} className="underline">Back to account</button></div>}
  const artwork=order.artwork||{};
  const production=order.production||{};
  const delivery=order.deliveryStatus||{};
  const status=String(order.status||'').toUpperCase();
  const collectionReady=passState.pass?.status==='ready'||passState.pass?.status==='collected';
  const steps=[['Placed',true],['Artwork',artwork.count>0 || ['ARTWORK_CHECK','IN_PRODUCTION','QUALITY_CHECK','DISPATCHED'].includes(status)],['Production',production.count>0 || ['IN_PRODUCTION','QUALITY_CHECK','DISPATCHED'].includes(status)],['Quality / Packing',['QUALITY_CHECK','DISPATCHED'].includes(status)||production.status==='packing'],['Collection / Dispatch',collectionReady||status==='DISPATCHED'||delivery.status==='dispatched']];
  const orderId=order.id||order.orderNumber;
  const email=order.customer?.email||order.customerEmail||'';
  const tax=buildOrderVatSummary(order);

  return <section className="py-6">
    <div className="mx-auto max-w-[1100px] px-4">
      <div className="mb-4 flex flex-wrap items-end justify-between gap-3">
        <div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#7B3FE4]">Order detail</div><h1 className="text-[28px] font-black">Order #{order.orderNumber||order.id}</h1></div>
        <button onClick={()=>navigate('/account')} className="px-4 py-2 border rounded-full text-[11px] font-bold uppercase tracking-[0.08em]">Back to account</button>
      </div>
      <div className="grid gap-3 md:grid-cols-5 mb-5">{steps.map(([label,active])=><Step key={label} label={label} active={active} />)}</div>
      <div className="grid gap-4 md:grid-cols-2">
        <Card title="Items">{(order.items||[]).length?order.items.map((item)=><div key={item.id||item.productName||item.titleSnapshot} className="mb-2 flex justify-between gap-3"><span>{item.productName||item.titleSnapshot||item.name||'Print item'} × {item.quantity||item.qty||1}<span className="ml-2 text-[10px] uppercase tracking-[0.08em] text-[#18A7D0]">{item.vatRate!==undefined?`${item.vatRate}% VAT`:''}</span></span><span>{currency(item.totalPrice||moneyFromMinor(item.grossTotalMinor)||moneyFromMinor(item.totalMinor))}</span></div>):<div>Order item details are syncing.</div>}<div className="mt-3 grid gap-1 border-t pt-3" style={{borderColor:'#E3E8F0'}}><div className="flex justify-between"><span>Net</span><b className="text-[#161A22]">{currency(tax.net)}</b></div><div className="flex justify-between"><span>VAT</span><b className="text-[#161A22]">{currency(tax.vat)}</b></div><div className="flex justify-between font-bold text-[#161A22]"><span>Total inc. VAT</span><span>{currency(tax.gross)}</span></div></div></Card>
        <VatSummary order={order} />
        <CollectionPassCard passState={passState} />
        <Card title="Artwork"><div style={{color:tone(artwork.status)}} className="font-bold">{nice(artwork.status||order.artwork_status||'Awaiting artwork')}</div>{artwork.count? <div>{artwork.count} artwork file(s) linked.</div>:<div>No artwork file linked yet.</div>}{(artwork.items||[]).slice(0,4).map((file)=><div key={file.id} className="mt-2 rounded-[12px] border bg-[#FBFCFF] px-3 py-2" style={{borderColor:'#E3E8F0'}}><div className="font-bold text-[#161A22]">{file.originalName||file.id}</div><div>{nice(file.reviewStatus||'pending-review')}</div>{file.downloadUrl?<a href={file.downloadUrl} target="_blank" className="underline text-[#18A7D0]">View file</a>:null}</div>)}<button onClick={()=>navigate('/artwork-upload')} className="mt-3 px-4 py-2 bg-black text-white rounded-full text-[11px] font-bold uppercase tracking-[0.08em]">Upload artwork</button></Card>
        <Card title="Production"><div style={{color:tone(production.status)}} className="font-bold">{nice(production.status||'Not started')}</div>{production.latest?<><div>Machine: {production.latest.machine||'Unassigned'}</div><div>Due: {production.latest.dueDate||'TBC'}</div><div>Priority: {nice(production.latest.priority||'normal')}</div></>:<div>Production will start after artwork approval.</div>}{(production.items||[]).slice(0,3).map((job)=><div key={job.id} className="mt-2 rounded-[12px] border bg-[#FBFCFF] px-3 py-2" style={{borderColor:'#E3E8F0'}}>{job.productName} — {nice(job.status)}</div>)}</Card>
        <Card title="Delivery / collection"><div style={{color:tone(delivery.status||passState.pass?.status)}} className="font-bold">{passState.pass?nice(passState.pass.status):nice(delivery.status||'Not dispatched')}</div><div>Method: {passState.pass?.locationLabel||delivery.method||order.delivery||'Standard'}</div>{delivery.carrier?<div>Carrier: {delivery.carrier}</div>:null}{delivery.trackingNumber?<div>Tracking: <span className="font-bold text-[#161A22]">{delivery.trackingNumber}</span></div>:passState.pass?<div>Collection PIN: <span className="font-bold text-[#161A22]">{passState.pass.pin}</span></div>:<div>Tracking/collection details will appear once ready.</div>}</Card>
        <Card title="Documents"><div className="flex flex-wrap gap-2"><button onClick={()=>openOrderDocument(orderId,'invoice',email)} className="text-[11px] border px-3 py-1 rounded-full font-bold uppercase tracking-[0.08em]">Download invoice</button><button onClick={()=>openOrderDocument(orderId,'receipt',email)} className="text-[11px] border px-3 py-1 rounded-full font-bold uppercase tracking-[0.08em]">Download receipt</button></div><div className="mt-2">Invoice and receipt PDFs are generated from the live order/payment record.</div><div className="mt-2" style={{color:tone(order.paymentStatus)}}>Payment: {nice(order.paymentStatus||'unpaid')}</div></Card>
        <Card title="Need help?"><div>Contact support with order number <b className="text-[#161A22]">{order.orderNumber||order.id}</b>.</div><button onClick={()=>navigate('/bespoke-quote')} className="mt-3 px-4 py-2 border rounded-full text-[11px] font-bold uppercase tracking-[0.08em]">Contact support</button></Card>
      </div>
    </div>
  </section>
}
